spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/diploma_db
    username: postgres
    password: password
  flyway:
    url: jdbc:postgresql://localhost:5432/diploma_db
    user: postgres
    password: password
