object Deps {
    const val gradle              = "6.8.3"
    const val javaGlobal          = "11"
    const val kotlinGlobal        = "1.4.31"
    const val nodeJS              = "14.16.0"
    const val nodeJSGradlePlugin  = "3.0.1"
    const val assertJCore         = "3.17.2"
    const val junitJupiter        = "5.7.0"
    const val findbugsJsr305      = "3.0.2"
    const val mockitoCore         = "3.6.0"
    const val mapstruct           = "1.4.1.Final"
    const val pdfBox              = "2.0.21"
    const val jsonWebToken        = "0.9.1"
    const val testcontainers      = "1.14.0"
    const val flywayGradlePlugin  = "7.0.0"
    const val springBoot          = "2.4.2"
    const val springDepManagement = "1.0.11.RELEASE"
    const val logback             = "1.2.3"
    const val slf4j               = "1.7.30"
}