spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    hikari:
      auto-commit: false
    data:
      jpa:
        repositories:
          bootstrap-mode: deferred
  jpa:
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate.format_sql: true
      hibernate.id.new_generator_mappings: true
      hibernate.connection.autocommit: false
      hibernate.connection.provider_disables_autocommit: true
      hibernate.proc.param_null_passing: true
      hibernate.generate_statistics: false
      hibernate.jdbc.time_zone: UTC
      hibernate.jdbc.batch_versioned_data: true
      hibernate.jdbc.batch_size: 25
      hibernate.jdbc.fetch_size: 100
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true