spring:
  jpa:
    properties:
      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      hibernate.cache.hazelcast.instance_name: diploma-server
      hibernate.cache.hazelcast.use_lite_member: true
      hibernate.cache.use_minimal_puts: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
